<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYo8ognz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYo8ognz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYo8ognz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYo8ognz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYo8ognz\appProdProjectContainer([
    'container.build_hash' => 'Yo8ognz',
    'container.build_id' => '55436e20',
    'container.build_time' => 1560620483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYo8ognz');
