<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmfcfxa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmfcfxa/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUmfcfxa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUmfcfxa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUmfcfxa\appProdProjectContainer([
    'container.build_hash' => 'Umfcfxa',
    'container.build_id' => '0678aa57',
    'container.build_time' => 1560451511,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmfcfxa');
